<a href="https://colab.research.google.com/github/Amal-Baby-Mathews/Pytorch_abm/blob/main/Pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip show torch

Name: torch
Version: 2.6.0+cu124
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3-Clause
Location: /usr/local/lib/python3.11/dist-packages
Requires: filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvtx-cu12, sympy, triton, typing-extensions
Required-by: accelerate, fastai, peft, sentence-transformers, timm, torchaudio, torchdata, torchvision


In [2]:
import torch
import numpy as np

In [3]:
#tensor with numbers one to 16 in shape (4,4)
tensor = torch.arange(1,17).reshape(4,4)
print(tensor)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])


In [4]:
#first row
print("first row:",tensor[0])
print(tensor[:,0],"first column")
print(tensor[...,-1],"last column")
print(tensor[-1],"last row")

first row: tensor([1, 2, 3, 4])
tensor([ 1,  5,  9, 13]) first column
tensor([ 4,  8, 12, 16]) last column
tensor([13, 14, 15, 16]) last row


In [5]:
agg=tensor[0].sum()
#convert tensor to np array:
array=tensor.numpy()
print(array)
print(agg)
agg_item=agg.item()
print(agg_item)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
tensor(10)
10


In [6]:
a=tensor
print(a,"print a")
b=tensor[1]
print(b,"print b")
c=a + b.T
print("Broadcasted tensor", c)

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]]) print a
tensor([5, 6, 7, 8]) print b
Broadcasted tensor tensor([[ 6,  8, 10, 12],
        [10, 12, 14, 16],
        [14, 16, 18, 20],
        [18, 20, 22, 24]])


<ipython-input-6-3974751657>:5: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:3725.)
  c=a + b.T


In [7]:
print(torch.device("cuda" if torch.cuda.is_available() else "cpu"))

cuda


In [12]:
gpu_data=tensor.cuda()
print(tensor.device)
print(gpu_data.device)
cpu_data=gpu_data.to("cpu")
print(cpu_data.device)

cpu
cuda:0
cpu
